version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - ${CODEBUILD_SRC_DIR}/scripts/install.sh
    finally:
      - echo Install phase finished
  pre_build:
    commands:
      - ${CODEBUILD_SRC_DIR}/scripts/pre_build.sh
    finally:
      - echo Pre-build phase finished
  build:
    commands:
      - ${CODEBUILD_SRC_DIR}/scripts/build.sh
    finally:
      - echo Build phase finished
  post_build:
    commands:
      - ${CODEBUILD_SRC_DIR}/scripts/post_build.sh
    finally:
      - echo Post-build phase finished
artifacts:
  files:
    - "**/*"
  base-directory: $CODEBUILD_SRC_DIR/public/
  discard-paths: no
